"""
Build database/synth_kb_sample.jsonl — a small, stratified, COMMITTED
sample of database/synth_kb.jsonl.

database/real_kb.jsonl and database/synth_kb.jsonl are both gitignored
(regenerated by the data pipeline, not source-controlled — see
database/README.md). That means anyone who clones this repo has no way to
see or reproduce the corpus behind the evaluation numbers. This script
produces a small representative sample that DOES get committed,
stratified proportionally by source spec (via the same _extract_spec()
used in scripts/build_synth_kb.py's summary table) so the sample's spec
mix matches the full corpus.

Usage:
    uv run python scripts/make_kb_sample.py
    uv run python scripts/make_kb_sample.py --sample-size 150 --seed 42
"""
from __future__ import annotations

import json
import random
import sys
from pathlib import Path

import typer
from rich.console import Console
from rich.table import Table

sys.path.insert(0, str(Path(__file__).resolve().parents[1] ))

from scripts.build_synth_kb import _extract_spec

app = typer.Typer(add_completion=False)
console = Console()


def _load_jsonl(path: Path) -> list[dict]:
    rows = []
    with path.open() as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def _stratified_counts(spec_sizes: dict[str, int], sample_size: int) -> dict[str, int]:
    """
    Largest-remainder apportionment: allocate `sample_size` samples across
    specs proportional to spec_sizes, so the allocated counts sum to
    exactly sample_size. Caller guarantees sample_size <= sum(spec_sizes),
    which also guarantees no spec's allocation can exceed its own size
    (target_i = sample_size * n_i/total <= n_i whenever sample_size <= total).
    """
    total = sum(spec_sizes.values())
    exact = {spec: sample_size * n / total for spec, n in spec_sizes.items()}
    counts = {spec: int(v) for spec, v in exact.items()}  # floor
    remainder = sample_size - sum(counts.values())
    # Give the leftover units to the specs with the largest fractional part
    # (standard largest-remainder / Hamilton apportionment).
    by_fraction = sorted(spec_sizes, key=lambda s: exact[s] - counts[s], reverse=True)
    for spec in by_fraction[:remainder]:
        counts[spec] += 1
    return counts


@app.command()
def main(
    input: Path = typer.Option(
        Path("database/synth_kb.jsonl"), "--input", "-i",
        help="Full KB JSONL to sample from",
    ),
    out: Path = typer.Option(
        Path("database/synth_kb_sample.jsonl"), "--out", "-o",
        help="Committed sample output path",
    ),
    sample_size: int = typer.Option(
        150, "--sample-size",
        help="Target total rows in the sample. If the full KB has fewer "
             "rows than this, the whole file is copied instead of erroring.",
    ),
    seed: int = typer.Option(42, "--seed", help="Random seed for reproducibility"),
) -> None:
    """Write a stratified, proportional sample of synth_kb.jsonl for committing to git."""
    if not input.exists():
        console.print(f"[red]Input file not found: {input}[/red]")
        console.print("Run [bold]uv run python scripts/build_synth_kb.py[/bold] first.")
        raise typer.Exit(1)

    console.print(f"\n[bold]TeleTriage — Build KB Sample[/bold]")
    console.print(f"  Input:            {input}")
    console.print(f"  Output:           {out}")
    console.print(f"  Sample size:      {sample_size}")
    console.print(f"  Seed:             {seed}\n")

    rows = _load_jsonl(input)
    n_total = len(rows)

    by_spec: dict[str, list[dict]] = {}
    for row in rows:
        spec = _extract_spec(row.get("source", ""))
        by_spec.setdefault(spec, []).append(row)
    full_counts = {spec: len(group) for spec, group in by_spec.items()}

    rng = random.Random(seed)

    if n_total <= sample_size:
        console.print(
            f"[yellow]  Full KB has {n_total} rows <= sample size {sample_size} — "
            f"copying the whole file rather than sampling.[/yellow]\n"
        )
        sample_rows = rows
        sample_counts = dict(full_counts)
    else:
        target_counts = _stratified_counts(full_counts, sample_size)
        sample_rows = []
        sample_counts = {}
        for spec, group in by_spec.items():
            k = target_counts.get(spec, 0)
            picked = rng.sample(group, k)
            sample_rows.extend(picked)
            sample_counts[spec] = len(picked)

    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w") as fh:
        for row in sample_rows:
            fh.write(json.dumps(row, ensure_ascii=False) + "\n")

    # ─── Summary table ──────────────────────────────────────────────────────
    table = Table(title="Sample vs Full KB — by Source Spec", show_header=True, header_style="bold")
    table.add_column("Spec", style="cyan")
    table.add_column("Full KB", justify="right")
    table.add_column("Full %", justify="right")
    table.add_column("Sample", justify="right")
    table.add_column("Sample %", justify="right")

    for spec in sorted(full_counts, key=lambda s: -full_counts[s]):
        full_n = full_counts[spec]
        sample_n = sample_counts.get(spec, 0)
        table.add_row(
            spec,
            str(full_n),
            f"{100 * full_n / n_total:.0f}%",
            str(sample_n),
            f"{100 * sample_n / max(len(sample_rows), 1):.0f}%",
        )
    console.print(table)

    console.print(f"\n  Full KB:   {n_total} rows")
    console.print(f"  Sample:    {len(sample_rows)} rows")
    console.print(f"\n  Saved → [bold]{out}[/bold]\n")


if __name__ == "__main__":
    app()
